name: Flight Price Monitor

on:
  schedule:
    # Run every 3 days at 8 AM EST (1 PM UTC)
    - cron: '0 13 */3 * *'
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  check-flights:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: List files in repository
      run: |
        echo "Current directory:"
        pwd
        echo "Files in repository:"
        ls -la
    
    - name: Run flight price monitor
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        PRICE_THRESHOLD: ${{ secrets.PRICE_THRESHOLD }}
      run: |
        python flight_moniter.py
    
    - name: Log completion
      run: |
        echo "Flight monitor completed at $(date)"